# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1236, 735)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(187, 187, 221);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Slits_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Slits_box.setGeometry(QtCore.QRect(10, 400, 361, 141))
        self.Slits_box.setStyleSheet("QGroupBox {\n"
"\n"
"    font-weight:bold;\n"
"\n"
"    border:1px solid gray;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"    margin-top:12px;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    left:10px;\n"
"\n"
"    padding:0 5px;\n"
"\n"
"}")
        self.Slits_box.setObjectName("Slits_box")
        self.WBS_label = QtWidgets.QLabel(self.Slits_box)
        self.WBS_label.setGeometry(QtCore.QRect(40, 20, 171, 16))
        self.WBS_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.WBS_label.setObjectName("WBS_label")
        self.FOE_label = QtWidgets.QLabel(self.Slits_box)
        self.FOE_label.setGeometry(QtCore.QRect(40, 80, 151, 16))
        self.FOE_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.FOE_label.setObjectName("FOE_label")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.Slits_box)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 100, 341, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.FOE_Motor_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.FOE_Motor_Button.setObjectName("FOE_Motor_Button")
        self.horizontalLayout_5.addWidget(self.FOE_Motor_Button)
        self.FOE_Close_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.FOE_Close_Button.setObjectName("FOE_Close_Button")
        self.horizontalLayout_5.addWidget(self.FOE_Close_Button)
        self.FOE_Ref_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.FOE_Ref_Button.setObjectName("FOE_Ref_Button")
        self.horizontalLayout_5.addWidget(self.FOE_Ref_Button)
        self.FOE_Open_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.FOE_Open_Button.setObjectName("FOE_Open_Button")
        self.horizontalLayout_5.addWidget(self.FOE_Open_Button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Slits_box)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 341, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WBS_Motor_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.WBS_Motor_Button.setObjectName("WBS_Motor_Button")
        self.horizontalLayout_4.addWidget(self.WBS_Motor_Button)
        self.WBS_Close_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.WBS_Close_Button.setObjectName("WBS_Close_Button")
        self.horizontalLayout_4.addWidget(self.WBS_Close_Button)
        self.WBS_Ref_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.WBS_Ref_Button.setObjectName("WBS_Ref_Button")
        self.horizontalLayout_4.addWidget(self.WBS_Ref_Button)
        self.WBS_Open_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.WBS_Open_Button.setObjectName("WBS_Open_Button")
        self.horizontalLayout_4.addWidget(self.WBS_Open_Button)
        self.WBS_status_led = QtWidgets.QLabel(self.Slits_box)
        self.WBS_status_led.setGeometry(QtCore.QRect(20, 20, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WBS_status_led.sizePolicy().hasHeightForWidth())
        self.WBS_status_led.setSizePolicy(sizePolicy)
        self.WBS_status_led.setMinimumSize(QtCore.QSize(10, 10))
        self.WBS_status_led.setMaximumSize(QtCore.QSize(16, 16))
        self.WBS_status_led.setStyleSheet("QLabel{ background-color: rgb(120,120,120); border-radius: 8px; border: 1px solid black; }")
        self.WBS_status_led.setText("")
        self.WBS_status_led.setObjectName("WBS_status_led")
        self.FOE_status_led = QtWidgets.QLabel(self.Slits_box)
        self.FOE_status_led.setGeometry(QtCore.QRect(20, 80, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FOE_status_led.sizePolicy().hasHeightForWidth())
        self.FOE_status_led.setSizePolicy(sizePolicy)
        self.FOE_status_led.setMinimumSize(QtCore.QSize(16, 16))
        self.FOE_status_led.setMaximumSize(QtCore.QSize(16, 16))
        self.FOE_status_led.setStyleSheet("QLabel{ background-color: rgb(120,120,120); border-radius: 8px; border: 1px solid black; }")
        self.FOE_status_led.setText("")
        self.FOE_status_led.setObjectName("FOE_status_led")
        self.DVF_box = QtWidgets.QGroupBox(self.centralwidget)
        self.DVF_box.setGeometry(QtCore.QRect(10, 550, 361, 141))
        self.DVF_box.setStyleSheet("QGroupBox {\n"
"\n"
"    font-weight:bold;\n"
"\n"
"    border:1px solid gray;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"    margin-top:12px;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    left:10px;\n"
"\n"
"    padding:0 5px;\n"
"\n"
"}")
        self.DVF_box.setObjectName("DVF_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.DVF_box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DVF_ROI_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.DVF_ROI_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.DVF_ROI_label.setObjectName("DVF_ROI_label")
        self.gridLayout_3.addWidget(self.DVF_ROI_label, 0, 0, 1, 1)
        self.DVF_start_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.DVF_start_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.DVF_start_label.setObjectName("DVF_start_label")
        self.gridLayout_3.addWidget(self.DVF_start_label, 1, 0, 1, 1)
        self.ROI_shape_x_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ROI_shape_x_edit.setObjectName("ROI_shape_x_edit")
        self.gridLayout_3.addWidget(self.ROI_shape_x_edit, 0, 1, 1, 1)
        self.ROI_shape_y_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ROI_shape_y_edit.setObjectName("ROI_shape_y_edit")
        self.gridLayout_3.addWidget(self.ROI_shape_y_edit, 0, 2, 1, 1)
        self.ROI_start_x_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ROI_start_x_edit.setObjectName("ROI_start_x_edit")
        self.gridLayout_3.addWidget(self.ROI_start_x_edit, 1, 1, 1, 1)
        self.ROI_start_y_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ROI_start_y_edit.setObjectName("ROI_start_y_edit")
        self.gridLayout_3.addWidget(self.ROI_start_y_edit, 1, 2, 1, 1)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.DVF_box)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 90, 241, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ROI_Disable_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.ROI_Disable_Button.setObjectName("ROI_Disable_Button")
        self.horizontalLayout_6.addWidget(self.ROI_Disable_Button)
        self.ROI_Define_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.ROI_Define_Button.setObjectName("ROI_Define_Button")
        self.horizontalLayout_6.addWidget(self.ROI_Define_Button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.DVF_box)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(260, 20, 91, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DVF_Acq_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DVF_Acq_Button.sizePolicy().hasHeightForWidth())
        self.DVF_Acq_Button.setSizePolicy(sizePolicy)
        self.DVF_Acq_Button.setObjectName("DVF_Acq_Button")
        self.verticalLayout_2.addWidget(self.DVF_Acq_Button)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DVF_status_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.DVF_status_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.DVF_status_label.setObjectName("DVF_status_label")
        self.horizontalLayout_10.addWidget(self.DVF_status_label)
        self.DVF_status_led = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DVF_status_led.sizePolicy().hasHeightForWidth())
        self.DVF_status_led.setSizePolicy(sizePolicy)
        self.DVF_status_led.setMinimumSize(QtCore.QSize(16, 16))
        self.DVF_status_led.setMaximumSize(QtCore.QSize(16, 16))
        self.DVF_status_led.setStyleSheet("QLabel{ background-color: rgb(120,120,120); border-radius: 8px; border: 1px solid black; }")
        self.DVF_status_led.setText("")
        self.DVF_status_led.setObjectName("DVF_status_led")
        self.horizontalLayout_10.addWidget(self.DVF_status_led)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.Und_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Und_box.setGeometry(QtCore.QRect(10, 0, 1201, 401))
        self.Und_box.setStyleSheet("QGroupBox {\n"
"\n"
"    font-weight:bold;\n"
"\n"
"    border:1px solid gray;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"    margin-top:12px;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    left:10px;\n"
"\n"
"    padding:0 5px;\n"
"\n"
"}")
        self.Und_box.setObjectName("Und_box")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Und_box)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 141, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Und_status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Und_status_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.Und_status_label.setObjectName("Und_status_label")
        self.horizontalLayout_9.addWidget(self.Und_status_label)
        self.Und_status_led = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Und_status_led.sizePolicy().hasHeightForWidth())
        self.Und_status_led.setSizePolicy(sizePolicy)
        self.Und_status_led.setMinimumSize(QtCore.QSize(16, 16))
        self.Und_status_led.setMaximumSize(QtCore.QSize(16, 16))
        self.Und_status_led.setStyleSheet("QLabel{ background-color: rgb(120,120,120); border-radius: 8px; border: 1px solid black; }")
        self.Und_status_led.setText("")
        self.Und_status_led.setObjectName("Und_status_led")
        self.horizontalLayout_9.addWidget(self.Und_status_led)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.Und_Connect_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Und_Connect_Button.sizePolicy().hasHeightForWidth())
        self.Und_Connect_Button.setSizePolicy(sizePolicy)
        self.Und_Connect_Button.setObjectName("Und_Connect_Button")
        self.verticalLayout.addWidget(self.Und_Connect_Button)
        self.Und_Phase_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Und_Phase_Button.sizePolicy().hasHeightForWidth())
        self.Und_Phase_Button.setSizePolicy(sizePolicy)
        self.Und_Phase_Button.setObjectName("Und_Phase_Button")
        self.verticalLayout.addWidget(self.Und_Phase_Button)
        self.Und_Move_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Und_Move_Button.sizePolicy().hasHeightForWidth())
        self.Und_Move_Button.setSizePolicy(sizePolicy)
        self.Und_Move_Button.setObjectName("Und_Move_Button")
        self.verticalLayout.addWidget(self.Und_Move_Button)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Und_box)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 110, 121, 191))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.DCM_status_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.DCM_status_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.DCM_status_label.setObjectName("DCM_status_label")
        self.horizontalLayout_11.addWidget(self.DCM_status_label)
        self.DCM_status_led = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCM_status_led.sizePolicy().hasHeightForWidth())
        self.DCM_status_led.setSizePolicy(sizePolicy)
        self.DCM_status_led.setMinimumSize(QtCore.QSize(16, 16))
        self.DCM_status_led.setMaximumSize(QtCore.QSize(16, 16))
        self.DCM_status_led.setStyleSheet("QLabel{ background-color: rgb(120,120,120); border-radius: 8px; border: 1px solid black; }")
        self.DCM_status_led.setText("")
        self.DCM_status_led.setObjectName("DCM_status_led")
        self.horizontalLayout_11.addWidget(self.DCM_status_led)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.DCM_Connect_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCM_Connect_Button.sizePolicy().hasHeightForWidth())
        self.DCM_Connect_Button.setSizePolicy(sizePolicy)
        self.DCM_Connect_Button.setObjectName("DCM_Connect_Button")
        self.verticalLayout_3.addWidget(self.DCM_Connect_Button)
        self.DCM_Move_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCM_Move_Button.sizePolicy().hasHeightForWidth())
        self.DCM_Move_Button.setSizePolicy(sizePolicy)
        self.DCM_Move_Button.setObjectName("DCM_Move_Button")
        self.verticalLayout_3.addWidget(self.DCM_Move_Button)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Und_box)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 271, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.energy_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.energy_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.energy_label.setObjectName("energy_label")
        self.horizontalLayout_2.addWidget(self.energy_label)
        self.Energy_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.Energy_edit.setObjectName("Energy_edit")
        self.horizontalLayout_2.addWidget(self.Energy_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.harmonic_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.harmonic_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.harmonic_label.setObjectName("harmonic_label")
        self.horizontalLayout_3.addWidget(self.harmonic_label)
        self.Harmonic_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Harmonic_edit.sizePolicy().hasHeightForWidth())
        self.Harmonic_edit.setSizePolicy(sizePolicy)
        self.Harmonic_edit.setObjectName("Harmonic_edit")
        self.horizontalLayout_3.addWidget(self.Harmonic_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.Und_Phase_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Und_Phase_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.Und_Phase_label.setObjectName("Und_Phase_label")
        self.verticalLayout_4.addWidget(self.Und_Phase_label)
        self.graphicsViewAPU = QtWidgets.QGraphicsView(self.Und_box)
        self.graphicsViewAPU.setGeometry(QtCore.QRect(300, 50, 261, 81))
        self.graphicsViewAPU.setObjectName("graphicsViewAPU")
        self.FieldplotWidget = QtWidgets.QWidget(self.Und_box)
        self.FieldplotWidget.setGeometry(QtCore.QRect(300, 160, 351, 221))
        self.FieldplotWidget.setObjectName("FieldplotWidget")
        self.SpectrumplotWidget = QtWidgets.QWidget(self.Und_box)
        self.SpectrumplotWidget.setGeometry(QtCore.QRect(670, 20, 521, 301))
        self.SpectrumplotWidget.setObjectName("SpectrumplotWidget")
        self.ERangeLabelMin = QtWidgets.QLabel(self.Und_box)
        self.ERangeLabelMin.setGeometry(QtCore.QRect(780, 350, 81, 31))
        self.ERangeLabelMin.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.ERangeLabelMin.setObjectName("ERangeLabelMin")
        self.ERangeLabelMax = QtWidgets.QLabel(self.Und_box)
        self.ERangeLabelMax.setGeometry(QtCore.QRect(940, 350, 81, 31))
        self.ERangeLabelMax.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.ERangeLabelMax.setObjectName("ERangeLabelMax")
        self.ERange = QtWidgets.QLabel(self.Und_box)
        self.ERange.setGeometry(QtCore.QRect(780, 320, 101, 31))
        self.ERange.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.ERange.setObjectName("ERange")
        self.SpectrumSpinXMin = QtWidgets.QDoubleSpinBox(self.Und_box)
        self.SpectrumSpinXMin.setGeometry(QtCore.QRect(810, 350, 71, 31))
        self.SpectrumSpinXMin.setDecimals(1)
        self.SpectrumSpinXMin.setMaximum(20.0)
        self.SpectrumSpinXMin.setSingleStep(0.1)
        self.SpectrumSpinXMin.setObjectName("SpectrumSpinXMin")
        self.SpectrumSpinXMax = QtWidgets.QDoubleSpinBox(self.Und_box)
        self.SpectrumSpinXMax.setGeometry(QtCore.QRect(980, 350, 71, 31))
        self.SpectrumSpinXMax.setDecimals(1)
        self.SpectrumSpinXMax.setMinimum(1.0)
        self.SpectrumSpinXMax.setMaximum(20.0)
        self.SpectrumSpinXMax.setSingleStep(0.1)
        self.SpectrumSpinXMax.setProperty("value", 20.0)
        self.SpectrumSpinXMax.setObjectName("SpectrumSpinXMax")
        self.verticalSlider = QtWidgets.QSlider(self.Und_box)
        self.verticalSlider.setGeometry(QtCore.QRect(560, 20, 31, 141))
        self.verticalSlider.setStyleSheet("QSlider::handle:vertical {\n"
"\n"
"    border-image: url(:/icons/eye.png);\n"
"\n"
"    width:32px;\n"
"    height:32px;\n"
"\n"
"    margin:-12px -14px;\n"
"\n"
"    background:transparent;\n"
"    border:none;\n"
"}\n"
"QSlider::groove:vertical {\n"
"\n"
"    background: rgb(120,120,120);\n"
"\n"
"    width: 4px;\n"
"\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"\n"
"    background: rgb(120,120,120);\n"
"}")
        self.verticalSlider.setMinimum(-100)
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.Scan_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Scan_box.setGeometry(QtCore.QRect(380, 400, 301, 291))
        self.Scan_box.setStyleSheet("QGroupBox {\n"
"\n"
"    font-weight:bold;\n"
"\n"
"    border:1px solid gray;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"    margin-top:12px;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"\n"
"    subcontrol-origin: margin;\n"
"\n"
"    left:10px;\n"
"\n"
"    padding:0 5px;\n"
"\n"
"}")
        self.Scan_box.setObjectName("Scan_box")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Scan_box)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 281, 241))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Inputfile_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Inputfile_label.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.Inputfile_label.setObjectName("Inputfile_label")
        self.verticalLayout_5.addWidget(self.Inputfile_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.FileButton.setObjectName("FileButton")
        self.horizontalLayout.addWidget(self.FileButton)
        self.InputFile_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.InputFile_lineEdit.setObjectName("InputFile_lineEdit")
        self.horizontalLayout.addWidget(self.InputFile_lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.Scan_nrpoints = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Scan_nrpoints.setStyleSheet("QLabel {\n"
"    color: rgb(30,30,30);\n"
"    font-size: 10pt;\n"
"}")
        self.Scan_nrpoints.setObjectName("Scan_nrpoints")
        self.verticalLayout_5.addWidget(self.Scan_nrpoints)
        self.Scan_Button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Scan_Button.sizePolicy().hasHeightForWidth())
        self.Scan_Button.setSizePolicy(sizePolicy)
        self.Scan_Button.setObjectName("Scan_Button")
        self.verticalLayout_5.addWidget(self.Scan_Button)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1236, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrum measurement"))
        self.Slits_box.setTitle(_translate("MainWindow", "Slits"))
        self.WBS_label.setText(_translate("MainWindow", "White beam slit (WBS)"))
        self.FOE_label.setText(_translate("MainWindow", "Front-end slits (FOE)"))
        self.FOE_Motor_Button.setText(_translate("MainWindow", "Enable"))
        self.FOE_Close_Button.setText(_translate("MainWindow", "Close"))
        self.FOE_Ref_Button.setText(_translate("MainWindow", "Ref."))
        self.FOE_Open_Button.setText(_translate("MainWindow", "Open"))
        self.WBS_Motor_Button.setText(_translate("MainWindow", "Enable"))
        self.WBS_Close_Button.setText(_translate("MainWindow", "Close"))
        self.WBS_Ref_Button.setText(_translate("MainWindow", "Ref."))
        self.WBS_Open_Button.setText(_translate("MainWindow", "Open"))
        self.DVF_box.setTitle(_translate("MainWindow", "Detector"))
        self.DVF_ROI_label.setText(_translate("MainWindow", "ROI Shape (x, y):"))
        self.DVF_start_label.setText(_translate("MainWindow", "ROI Start point (x, y):"))
        self.ROI_shape_x_edit.setText(_translate("MainWindow", "110"))
        self.ROI_shape_y_edit.setText(_translate("MainWindow", "93"))
        self.ROI_start_x_edit.setText(_translate("MainWindow", "565"))
        self.ROI_start_y_edit.setText(_translate("MainWindow", "690"))
        self.ROI_Disable_Button.setText(_translate("MainWindow", "Reset ROI"))
        self.ROI_Define_Button.setText(_translate("MainWindow", "Set ROI"))
        self.DVF_Acq_Button.setText(_translate("MainWindow", "Start Acq."))
        self.DVF_status_label.setText(_translate("MainWindow", "Status:"))
        self.Und_box.setTitle(_translate("MainWindow", "Undulator and monochromator (DCM)"))
        self.Und_status_label.setText(_translate("MainWindow", "Undulator status:"))
        self.Und_Connect_Button.setText(_translate("MainWindow", "Connect"))
        self.Und_Phase_Button.setText(_translate("MainWindow", "Calc. Phase"))
        self.Und_Move_Button.setText(_translate("MainWindow", "Move"))
        self.DCM_status_label.setText(_translate("MainWindow", "DCM status:"))
        self.DCM_Connect_Button.setText(_translate("MainWindow", "Connect"))
        self.DCM_Move_Button.setText(_translate("MainWindow", "Move"))
        self.energy_label.setText(_translate("MainWindow", "Energy [KeV]:"))
        self.Energy_edit.setText(_translate("MainWindow", "0"))
        self.harmonic_label.setText(_translate("MainWindow", "Harmonic:"))
        self.Harmonic_edit.setText(_translate("MainWindow", "0"))
        self.Und_Phase_label.setText(_translate("MainWindow", "Phase:"))
        self.ERangeLabelMin.setText(_translate("MainWindow", "Min:"))
        self.ERangeLabelMax.setText(_translate("MainWindow", "Max:"))
        self.ERange.setText(_translate("MainWindow", "Energy range"))
        self.Scan_box.setTitle(_translate("MainWindow", "Scan"))
        self.Inputfile_label.setText(_translate("MainWindow", "Input File:"))
        self.FileButton.setText(_translate("MainWindow", "Browse"))
        self.Scan_nrpoints.setText(_translate("MainWindow", "Nr. points:"))
        self.Scan_Button.setText(_translate("MainWindow", "Start Scan"))
